## E-commerce analysis 
1. the objective is to understand the dataset in order to obtain valuable insights for the team

In [2]:
import pandas as pd

orders = pd.read_csv('../Data/raw/olist_orders_dataset.csv')

order_items = pd.read_csv(
    '../Data/raw/olist_order_items_dataset.csv'
)

products = pd.read_csv(
    '../Data/raw/olist_products_dataset.csv'
)

customers = pd.read_csv(
    '../Data/raw/olist_customers_dataset.csv'
)

payments = pd.read_csv(
    '../Data/raw/olist_order_payments_dataset.csv'
)

reviews = pd.read_csv(
    '../Data/raw/olist_order_reviews_dataset.csv'
)

In [3]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [4]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

In [5]:
orders.describe()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,99441,99441,99441,99441,99281,97658,96476,99441
unique,99441,99441,8,98875,90733,81018,95664,459
top,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2018-03-31 15:08:21,2018-02-27 04:31:10,2018-05-09 15:48:00,2018-05-14 20:02:44,2017-12-20 00:00:00
freq,1,1,96478,3,9,47,3,522

In [6]:
orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='str')

In [7]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [8]:
order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB

In [9]:
order_items.describe()

       order_item_id          price  freight_value
count  112650.000000  112650.000000  112650.000000
mean        1.197834     120.653739      19.990320
std         0.705124     183.633928      15.806405
min         1.000000       0.850000       0.000000
25%         1.000000      39.900000      13.080000
50%         1.000000      74.990000      16.260000
75%         1.000000     134.900000      21.150000
max        21.000000    6735.000000     409.680000

In [10]:
order_items.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='str')

In [11]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [12]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB

In [13]:
products.describe()

,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32341.000000,32341.000000,32341.000000,32949.000000,32949.000000,32949.000000,32949.000000
mean,48.476949,771.495285,2.188986,2276.472488,30.815078,16.937661,23.196728
std,10.245741,635.115225,1.736766,4282.038731,16.914458,13.637554,12.079047
min,5.000000,4.000000,1.000000,0.000000,7.000000,2.000000,6.000000
25%,42.000000,339.000000,1.000000,300.000000,18.000000,8.000000,15.000000
50%,51.000000,595.000000,1.000000,700.000000,25.000000,13.000000,20.000000
75%,57.000000,972.000000,3.000000,1900.000000,38.000000,21.000000,30.000000
max,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.000000,118.000000

In [14]:
products.columns

Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='str')

In [15]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [16]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB

In [17]:
customers.describe()

       customer_zip_code_prefix
count              99441.000000
mean               35137.474583
std                29797.938996
min                 1003.000000
25%                11347.000000
50%                24416.000000
75%                58900.000000
max                99990.000000

In [18]:
customers.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='str')

In [19]:
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [20]:
payments.info()

<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB

In [21]:
payments.describe()

       payment_sequential  payment_installments  payment_value
count       103886.000000         103886.000000  103886.000000
mean             1.092679              2.853349     154.100380
std              0.706584              2.687051     217.494064
min              1.000000              0.000000       0.000000
25%              1.000000              1.000000      56.790000
50%              1.000000              1.000000     100.000000
75%              1.000000              4.000000     171.837500
max             29.000000             24.000000   13664.080000

In [22]:
payments.columns

Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='str')

In [23]:
reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [24]:
reviews.info()

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 5.3 MB

In [25]:
reviews.describe()

       review_score
count  99224.000000
mean       4.086421
std        1.347579
min        1.000000
25%        4.000000
50%        5.000000
75%        5.000000
max        5.000000

In [26]:
reviews.columns

Index(['review_id', 'order_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='str')

2. Now we can build the main dataframe to work with

- Starts with merging orders with customers

In [27]:
df = orders.merge(customers, on='customer_id', how='left')

- Addign payments

In [28]:
df = df.merge(payments, on='order_id', how='left')

- Adding order items

In [29]:
df = df.merge(order_items, on='order_id', how='left')

- Adding Products

In [30]:
df = df.merge(products, on='product_id', how='left')

- Adding Reviews

In [31]:
df = df.merge(reviews, on='order_id', how='left')

In [32]:
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,product_weight_g,product_length_cm,product_height_cm,product_width_cm,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,500.0,19.0,8.0,13.0,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,500.0,19.0,8.0,13.0,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,500.0,19.0,8.0,13.0,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,...,400.0,19.0,13.0,19.0,8d5266042046a06655c8db133d120ba5,4.0,Muito boa a loja,Muito bom o produto.,2018-08-08 00:00:00,2018-08-08 18:37:50
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,420.0,24.0,19.0,21.0,e73b67b67587f7644d5bd1a52deb1b01,5.0,NaN,NaN,2018-08-18 00:00:00,2018-08-22 19:07:58

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 119143 entries, 0 to 119142
Data columns (total 36 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       119143 non-null  str
 1   customer_id                    119143 non-null  str
 2   order_status                   119143 non-null  str
 3   order_purchase_timestamp       119143 non-null  str
 4   order_approved_at              118966 non-null  str
 5   order_delivered_carrier_date   117057 non-null  str
 6   order_delivered_customer_date  115722 non-null  str
 7   order_estimated_delivery_date  119143 non-null  str
 8   customer_unique_id             119143 non-null  str
 9   customer_zip_code_prefix       119143 non-null  int64
 10  customer_city                  119143 non-null  str
 11  customer_state                 119143 non-null  str
 12  payment_sequential             119140 non-null  float64
 13  payment_type                   119140 non-null  str
 14  payment_installments           119140 non-null  float64
 15  payment_value                  119140 non-null  float64
 16  order_item_id                  118310 non-null  float64
 17  product_id                     118310 non-null  str
 18  seller_id                      118310 non-null  str
 19  shipping_limit_date            118310 non-null  str
 20  price                          118310 non-null  float64
 21  freight_value                  118310 non-null  float64
 22  product_category_name          116601 non-null  str
 23  product_name_lenght            116601 non-null  float64
 24  product_description_lenght     116601 non-null  float64
 25  product_photos_qty             116601 non-null  float64
 26  product_weight_g               118290 non-null  float64
 27  product_length_cm              118290 non-null  float64
 28  product_height_cm              118290 non-null  float64
 29  product_width_cm               118290 non-null  float64
 30  review_id                      118146 non-null  str
 31  review_score                   118146 non-null  float64
 32  review_comment_title           13989 non-null   str
 33  review_comment_message         50245 non-null   str
 34  review_creation_date           118146 non-null  str
 35  review_answer_timestamp        118146 non-null  str
dtypes: float64(14), int64(1), str(21)
memory usage: 32.7 MB

In [34]:
df.shape

(119143, 36)

- Saving a copy just in case

In [35]:
df_raw = df.copy()

3. Exploring nulls

In [36]:
df.isnull().sum().sort_values(ascending=False)

review_comment_title             105154
review_comment_message            68898
order_delivered_customer_date      3421
product_name_lenght                2542
product_category_name              2542
product_photos_qty                 2542
product_description_lenght         2542
order_delivered_carrier_date       2086
review_score                        997
review_id                           997
review_answer_timestamp             997
review_creation_date                997
product_weight_g                    853
product_length_cm                   853
product_width_cm                    853
product_height_cm                   853
shipping_limit_date                 833
seller_id                           833
product_id                          833
order_item_id                       833
freight_value                       833
price                               833
order_approved_at                   177
payment_value                         3
payment_installments                  3
payment_sequential                    3
payment_type                          3
order_id                              0
order_purchase_timestamp              0
order_status                          0
customer_id                           0
customer_unique_id                    0
customer_state                        0
customer_zip_code_prefix              0
customer_city                         0
order_estimated_delivery_date         0
dtype: int64

- We need to get rid of those null values that we can not evaluate

In [37]:
df = df.dropna(
    subset=[
        'product_id',
        'price',
        'freight_value'
    ]
)

In [38]:
df.isnull().sum().sort_values(ascending=False)

review_comment_title             104418
review_comment_message            68628
order_delivered_customer_date      2588
product_name_lenght                1709
product_category_name              1709
product_photos_qty                 1709
product_description_lenght         1709
order_delivered_carrier_date       1254
review_score                        978
review_id                           978
review_answer_timestamp             978
review_creation_date                978
product_weight_g                     20
product_length_cm                    20
product_width_cm                     20
product_height_cm                    20
order_approved_at                    15
payment_sequential                    3
payment_installments                  3
payment_value                         3
payment_type                          3
order_status                          0
customer_id                           0
order_id                              0
order_purchase_timestamp              0
shipping_limit_date                   0
customer_city                         0
customer_state                        0
order_estimated_delivery_date         0
seller_id                             0
product_id                            0
order_item_id                         0
customer_unique_id                    0
customer_zip_code_prefix              0
freight_value                         0
price                                 0
dtype: int64

- Also we noticed that the reviews score are too low, so we are going to fill results with the median

In [39]:
df['review_score'] = (
    df['review_score']
    .fillna(df['review_score'].median())
)

- And now we are going to filter for orders that are already delivered

In [40]:
df = df[df['order_status'] == 'delivered']

4. Convert the dates to use them

In [41]:
df.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'customer_unique_id', 'customer_zip_code_prefix', 'customer_city',
       'customer_state', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value', 'order_item_id', 'product_id',
       'seller_id', 'shipping_limit_date', 'price', 'freight_value',
       'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'review_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='str')

In [42]:
date_columns = [
    'order_purchase_timestamp',
    'order_approved_at',
    'shipping_limit_date',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date',
    'review_creation_date',
    'review_answer_timestamp'
]

for col in date_columns:
    df[col] = pd.to_datetime(df[col])

In [43]:
df.info()

<class 'pandas.DataFrame'>
Index: 115723 entries, 0 to 119142
Data columns (total 36 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       115723 non-null  str
 1   customer_id                    115723 non-null  str
 2   order_status                   115723 non-null  str
 3   order_purchase_timestamp       115723 non-null  datetime64[us]
 4   order_approved_at              115708 non-null  datetime64[us]
 5   order_delivered_carrier_date   115721 non-null  datetime64[us]
 6   order_delivered_customer_date  115715 non-null  datetime64[us]
 7   order_estimated_delivery_date  115723 non-null  datetime64[us]
 8   customer_unique_id             115723 non-null  str
 9   customer_zip_code_prefix       115723 non-null  int64
 10  customer_city                  115723 non-null  str
 11  customer_state                 115723 non-null  str
 12  payment_sequential             115720 non-null  float64
 13  payment_type                   115720 non-null  str
 14  payment_installments           115720 non-null  float64
 15  payment_value                  115720 non-null  float64
 16  order_item_id                  115723 non-null  float64
 17  product_id                     115723 non-null  str
 18  seller_id                      115723 non-null  str
 19  shipping_limit_date            115723 non-null  datetime64[us]
 20  price                          115723 non-null  float64
 21  freight_value                  115723 non-null  float64
 22  product_category_name          114085 non-null  str
 23  product_name_lenght            114085 non-null  float64
 24  product_description_lenght     114085 non-null  float64
 25  product_photos_qty             114085 non-null  float64
 26  product_weight_g               115703 non-null  float64
 27  product_length_cm              115703 non-null  float64
 28  product_height_cm              115703 non-null  float64
 29  product_width_cm               115703 non-null  float64
 30  review_id                      114862 non-null  str
 31  review_score                   115723 non-null  float64
 32  review_comment_title           13584 non-null   str
 33  review_comment_message         48095 non-null   str
 34  review_creation_date           114862 non-null  datetime64[us]
 35  review_answer_timestamp        114862 non-null  datetime64[us]
dtypes: datetime64[us](8), float64(14), int64(1), str(13)
memory usage: 32.7 MB

5. Creating Derived Columns

In [44]:
df['total_value'] = (
    df['price'] + df['freight_value']
)

df['delivery_delay'] = (
    df['order_delivered_customer_date']
    - df['order_estimated_delivery_date']
).dt.days

df['purchase_year'] = (
    df['order_purchase_timestamp'].dt.year
)

df['purchase_month'] = (
    df['order_purchase_timestamp'].dt.month
)

df['purchase_month_name'] = (
    df['order_purchase_timestamp']
    .dt.month_name()
)

6. Obtaining KPIs

Total Revenue
Total Orders
Average Order Value (grouped by order ID)
Average Review Score
Delayed Percentage
Most Used Payment Method
Top Categories
Revenue by State
Monthly Revenue

In [45]:
total_revenue = df['total_value'].sum()

total_orders = df['order_id'].nunique()

average_order_value = (
    df.groupby('order_id')['total_value']
    .sum()
    .mean()
)

average_review = df['review_score'].mean()

df['is_delayed'] = df['delivery_delay'] > 0
delayed_percentage = (
    df['is_delayed'].mean() * 100
)

most_used_payment = df['payment_type'].value_counts().index[0]

top_categories = (
    df.groupby('product_category_name')
    ['total_value']
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

revenue_by_state = (
    df.groupby('customer_state')
    ['total_value']
    .sum()
    .sort_values(ascending=False)
)
monthly_revenue = (
    df.groupby('purchase_month_name')
    ['total_value']
    .sum()
)

## Showing results
print(f"Total Revenue: {total_revenue}")
print(f"Total Orders: {total_orders}")
print(f"Average Order Value: {average_order_value}")
print(f"Average Review Score: {average_review}")
print(f"Delayed Orders Percentage: {delayed_percentage:.2f}%")
print(f"Most Used Payment Method: {most_used_payment}")
print(f"Top Categories:\n{top_categories}")
print(f"Revenue by State:\n{revenue_by_state}")
print(f"Monthly Revenue:\n{monthly_revenue}")

Total Revenue: 16188779.23
Total Orders: 96478
Average Order Value: 167.79762463981427
Average Review Score: 4.087329225823734
Delayed Orders Percentage: 6.53%
Most Used Payment Method: credit_card
Top Categories:
product_category_name
beleza_saude              1461349.75
relogios_presentes        1316696.84
cama_mesa_banho           1309729.85
esporte_lazer             1166307.34
informatica_acessorios    1077483.63
moveis_decoracao           931754.14
utilidades_domesticas      801521.45
cool_stuff                 722033.51
automotivo                 698077.73
ferramentas_jardim         595367.38
Name: total_value, dtype: float64
Revenue by State:
customer_state
SP    6076438.89
RJ    2167521.77
MG    1890600.24
RS     908920.14
PR     812671.95
BA     627081.41
SC     616385.81
DF     360530.87
GO     355374.39
ES     328955.10
PE     321062.12
CE     281430.06
PA     219300.64
MT     186000.71
MA     151814.71
PB     148333.53
MS     139757.80
RN     113567.01
PI     111665.76
AL      97724.79
SE      72694.76
TO      68355.46
RO      58089.48
AM      28298.78
AC      20767.13
AP      16396.40
RR       9039.52
Name: total_value, dtype: float64
Monthly Revenue:
purchase_month_name
April        1588670.95
August       1701199.83
December      877523.29
February     1303189.88
January      1266548.38
July         1677258.63
June         1583072.96
March        1615018.65
May          1786500.33
November     1205033.35
October       837721.08
September     747041.90
Name: total_value, dtype: float64

7. Obtaining valuable insights

- Which payment methods are dominating?

In [46]:
df['payment_type'].value_counts()

payment_type
credit_card    85372
boleto         22505
voucher         6181
debit_card      1662
Name: count, dtype: int64

- Which categories are generating the most revenue?

In [47]:
top_categories = (
    df.groupby('product_category_name')
    ['total_value']
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

top_categories

product_category_name
beleza_saude              1461349.75
relogios_presentes        1316696.84
cama_mesa_banho           1309729.85
esporte_lazer             1166307.34
informatica_acessorios    1077483.63
moveis_decoracao           931754.14
utilidades_domesticas      801521.45
cool_stuff                 722033.51
automotivo                 698077.73
ferramentas_jardim         595367.38
Name: total_value, dtype: float64

- Which states generate the most sales?

In [48]:
revenue_by_state = (
    df.groupby('customer_state')
    ['total_value']
    .sum()
    .sort_values(ascending=False)
)

revenue_by_state.head(10)

customer_state
SP    6076438.89
RJ    2167521.77
MG    1890600.24
RS     908920.14
PR     812671.95
BA     627081.41
SC     616385.81
DF     360530.87
GO     355374.39
ES     328955.10
Name: total_value, dtype: float64

- Do late deliveries affect reviews?

In [49]:
df.groupby('is_delayed')['review_score'].mean()

is_delayed
False    4.210632
True     2.322704
Name: review_score, dtype: float64

- Which categories have best/worst reviews?

In [50]:
review_counts = (
    df.groupby('product_category_name')
    ['review_score']
    .count()
)

review_means = (
    df.groupby('product_category_name')
    ['review_score']
    .mean()
)

category_reviews = pd.DataFrame({
    'review_count': review_counts,
    'average_review': review_means
})

category_reviews = (
    category_reviews[
        category_reviews['review_count'] >= 100
    ]
    .sort_values(
        by='average_review',
        ascending=False
    )
)

category_reviews.head(10)

                                    review_count  average_review
product_category_name
livros_interesse_geral                       549        4.506375
construcao_ferramentas_ferramentas           105        4.438095
livros_tecnicos                              268        4.402985
alimentos_bebidas                            281        4.387900
malas_acessorios                            1148        4.332753
alimentos                                    515        4.289320
fashion_calcados                             273        4.285714
papelaria                                   2572        4.240280
pcs                                          216        4.236111
eletroportateis                              684        4.235380

In [51]:
category_reviews.tail(10)

                         review_count  average_review
product_category_name
casa_construcao                   627        3.979266
moveis_decoracao                 8643        3.970381
moveis_sala                       524        3.965649
moveis_quarto                     119        3.941176
casa_conforto                     473        3.932347
cama_mesa_banho                 11814        3.927120
audio                             379        3.857520
telefonia_fixa                    262        3.770992
fashion_roupa_masculina           138        3.659420
moveis_escritorio                1763        3.565513

- Revenue over time

In [52]:
monthly_revenue = (
    df.groupby(
        ['purchase_year', 'purchase_month']
    )['total_value']
    .sum()
)

monthly_revenue

purchase_year  purchase_month
2016           9                     143.46
               10                  48314.12
               12                     19.62
2017           1                  138323.99
               2                  286678.44
               3                  442061.00
               4                  414527.46
               5                  614885.90
               6                  518076.28
               7                  610664.84
               8                  680858.92
               9                  746898.44
               10                 789406.96
               11                1205033.35
               12                 877503.67
2018           1                 1128224.39
               2                 1016511.44
               3                 1172957.65
               4                 1174143.49
               5                 1171614.43
               6                 1064996.68
               7                 1066593.79
               8                 1020340.91
Name: total_value, dtype: float64

- Saving the data processed

In [53]:
final_df = df[
    [
        'order_id',
        'customer_state',
        'product_category_name',
        'payment_type',
        'review_score',
        'total_value',
        'delivery_delay',
        'is_delayed',
        'purchase_year',
        'purchase_month',
        'purchase_month_name',
        'order_purchase_timestamp'
    ]
]

final_df.to_csv(
    '../data/processed/final_dashboard_dataset.csv',
    index=False
)